# ---- Base image ----
FROM node:24
WORKDIR /app

# ---- Install dependencies ----
COPY package*.json ./
RUN npm install

# ---- Expose dev port ----
EXPOSE 3000

# ---- Start dev server ----
CMD ["npm", "run", "dev"]
