services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: nuxt-frontend
    container_name: nuxt-frontend
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app # Local folder : Container folder (This creates a two-way sync between: Host (your Mac): frontend, & Container: /app/)
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    image: express-backend
    container_name: express-backend
    env_file:
      - .env
    ports:
      - "3001:3001"
    volumes:
      - ./server:/server
      - /server/node_modules
    working_dir: /server
    command: npm run dev
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p\"$DB_PASSWORD\""]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 30s

volumes:
  db_data: